### ISSUE TITLE
Error when using 'Run VESPER Kriging' and 'Import Vesper Results' tools

### ISSUE THREAD

**Issue by cratcliff** [CSIRO-Precision-Agriculture/PAT_QGIS_Plugin#33]
Running **Run VESPER Kriging** tool is producing the following error
> Could not import from VESPER to raster TIFF possibly due to a VESPER error.

Running **Import Vesper Results** tool is producing the following error
> NoneType' object has no attribute 'color1'
> 	Traceback (most recent call last):
> 	  File "C:/Users/XXX/.qgis2/python/plugins\pat\gui\postVesper_dialog.py", line 293, in accept 
	    color_ramp=raster_sym['colour_ramp'])
> 			  File "C:/Users/XXX/.qgis2/python/plugins\pat\util\qgis_symbology.py", line 82, in raster_apply_classified_renderer
> 			    rmp_colors = [ramp.color1().name()]   # the first
> 			AttributeError: 'NoneType' object has no attribute 'color1'

**Comment by cratcliff** [comment]
This is due to the PAT symbols not being installed. Installation instructions can be found in chapter 4.3 of the user manual.
