### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found. for from scipy import stats

### ISSUE THREAD

**Issue by cratcliff** [CSIRO-Precision-Agriculture/PAT_QGIS_Plugin#46]
When using QGIS 3.14.15 and QGIS LTR 3.10.9 the following error occurs.

```
Couldn't load plugin 'pat' due to an error when calling its classFactory() method 

ImportError: DLL load failed: The specified module could not be found. 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/MyUserAcc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pat\__init__.py", line 132, in classFactory
    from .pat_toolbar import pat_toolbar
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/MyUserAcc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pat\pat_toolbar.py", line 61, in 
    from .gui.blockGrid_dialog import BlockGridDialog
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/MyUserAcc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pat\gui\blockGrid_dialog.py", line 45, in 
    from util.qgis_symbology import RASTER_SYMBOLOGY, raster_apply_unique_value_renderer
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\MyUserAcc\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pat\util\qgis_symbology.py", line 38, in 
    from scipy import stats
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\scipy\stats\__init__.py", line 384, in 
    from .stats import *
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\scipy\stats\stats.py", line 179, in 
    from scipy.spatial.distance import cdist
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\scipy\spatial\__init__.py", line 102, in 
    from ._procrustes import procrustes
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\scipy\spatial\_procrustes.py", line 11, in 
    from scipy.linalg import orthogonal_procrustes
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\scipy\linalg\__init__.py", line 195, in 
    from .misc import *
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\scipy\linalg\misc.py", line 5, in 
    from .blas import get_blas_funcs
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS3~1.14\apps\Python37\lib\site-packages\scipy\linalg\blas.py", line 215, in 
    from scipy.linalg import _fblas
  File "C:/PROGRA~1/QGIS3~1.14/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by cratcliff** [comment]
This is due to a known fault in QGIS 3.14.15 and QGIS LTR 3.10.9 which is fixed in the next release. see https://github.com/qgis/QGIS/issues/38372
