### ISSUE TITLE
Error in Clean, Trim and Normalise Point Data - [None] not found in  axis

### ISSUE THREAD

**Issue by SEJimWilson** [CSIRO-Precision-Agriculture/PAT_QGIS_Plugin#57]
In the "Clean, Trim and Normalise point data" we are getting a consistent error across several different machines. We have tried several different versions of QGIS. See below for the version numbers and error codes.

Thanks

Jim
jim@soilessentials.com

![image](https://user-images.githubusercontent.com/80252678/110308472-0eb08b00-7ff8-11eb-911d-953794f82ec0.png)

PAT Enviroment
QGIS Environment :
    QGIS :              	3.16.3-Hannover
    Install Path :      	C:\Program Files\QGIS 3.16\apps\qgis
    Plugin Dir :        	C:\Users\jim.SE\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pat
    Temp Folder :       	C:\Users\jim.SE\AppData\Local\Temp
    Python :            	3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
    GDAL :              	3.1.4

PAT Version :
    PAT :               	1.0.3 2021-01-13T09:30:00.333616
    pyPrecAg :          	0.4.0
    Geopandas :         	0.7.0
    Rasterio :          	1.1.8
    Fiona :             	1.8.18
    Pandas :            	1.0.1

R Configuration :
    R Active :          	None
    R Install Folder :  	None

Errors..

2021-03-08T09:23:28     INFO    **************************************************
             Processing Clean, trim and normalise point data
2021-03-08T09:23:28     INFO    Parameters:---------------------------------------
              Layer: GasboardNorthEMI2021Jan_pts
              Process Field: DIPOLE1
              Thinning Distance: 1.0m
              Remove Zeros: False
              Standard Devs to Use: 3.0
              Trim Iteratively: True
              Output Projected Coordinate System: EPSG:32630 - WGS 84 / UTM zone 30N
              Saved CSV File: C:\Users\jim.SE\PAT\GasboardNorthEMI2021Jan_pts_DIPOLE1_normtrimmed.csv
2021-03-08T09:23:28     CRITICAL    '[None] not found in axis'
             Traceback (most recent call last):
              File "C:/Users/jim.SE/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pat\gui\cleanTrimPoints_wizard.py", line 1011, in accept
              gdfPoints.drop(xy_fields, axis=1, inplace=True)
              File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\pandas\core\frame.py", line 3997, in drop
              errors=errors,
              File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\pandas\core\generic.py", line 3936, in drop
              obj = obj._drop_axis(labels, axis, level=level, errors=errors)
              File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\pandas\core\generic.py", line 3970, in _drop_axis
              new_axis = axis.drop(labels, errors=errors)
              File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\pandas\core\indexes\base.py", line 5018, in drop
              raise KeyError(f"{labels[mask]} not found in axis")
             KeyError: '[None] not found in axis'

**Comment by cratcliff** [comment]
@SEJimWilson Thanks for submitting this error. I have created a workaround in the short term. Just re-install the PAT plugin in QGIS and try the tool again. 

A new version of PAT & pyprecag will be released shortly. Let me know if it doesn't fix your issue.

**Comment by SEJimWilson** [comment]
Christina,

Thanks for the quick reply. Will try this today.

Jim

**Comment by SEJimWilson** [comment]
Christina,

Just a confirmation that the problem seems to be solved on the 2 machines I’ve tested it on so far.

Thank You.
