### ISSUE TITLE
Isses starting PAT on QGIS 3.26

### ISSUE THREAD

**Issue by pnugentmsu** [CSIRO-Precision-Agriculture/PAT_QGIS_Plugin#65]
I just installed PAT and am getting the following error after installing and running the update dependences script on the desktop the uninstalling and reinstalling as suggested by the dialog. 

Couldn't load plugin 'pat' due to an error when calling its classFactory() method 

ImportError: DLL load failed while importing _version: The specified procedure could not be found. 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/t58m779/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pat\__init__.py", line 128, in classFactory
    from .pat_toolbar import pat_toolbar
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/t58m779/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pat\pat_toolbar.py", line 61, in 
    from .gui.blockGrid_dialog import BlockGridDialog
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/t58m779/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pat\gui\blockGrid_dialog.py", line 43, in 
    from util.qgis_common import (removeFileFromQGIS, addVectorFileToQGIS, addRasterFileToQGIS,
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\t58m779\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pat\util\qgis_common.py", line 33, in 
    import rasterio
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\rasterio\__init__.py", line 28, in 
    from rasterio._version import gdal_version, get_geos_version, get_proj_version
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: DLL load failed while importing _version: The specified procedure could not be found.

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.26.3-Buenos Aires Buenos Aires, 65e4edfdada 

Python Path:
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python
C:/Users/t58m779/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/t58m779/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.26.3\bin\python39.zip
C:\PROGRA~1\QGIS32~1.3\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib
C:\Program Files\QGIS 3.26.3\bin
C:\PROGRA~1\QGIS32~1.3\apps\Python39
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\Pythonwin
C:/Users/t58m779/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\t58m779\AppData\Roaming\QGIS\QGIS3\profiles\default\python\site-packages
C:\Users\t58m779\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pat

**Comment by lfrench0** [comment]
I also am having an issue with starting PAT, though I'm using QGIS 3.28. The errors seems to be similar though there are distinctions. I have also tried the 3.22 LTR version and also had issues there. The install of the PAT supporting dependencies 

Error:
>Couldn't load plugin 'pat' due to an error when calling its classFactory() method

> ImportError: DLL load failed while importing ogrext: The specified module could not be found. 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.1/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "%USERPROFILE%/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pat\__init__.py", line 128, in classFactory
    from .pat_toolbar import pat_toolbar
  File "C:\PROGRA~1/QGIS32~1.1/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "%USERPROFILE%/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pat\pat_toolbar.py", line 61, in 
    from .gui.blockGrid_dialog import BlockGridDialog
  File "C:\PROGRA~1/QGIS32~1.1/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "%USERPROFILE%/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pat\gui\blockGrid_dialog.py", line 48, in from pyprecag import config, processing
  File "C:\PROGRA~1/QGIS32~1.1/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\pyprecag\processing.py", line 45, in 
    from .convert import convert_polygon_to_grid, convert_grid_to_vesper, numeric_pixelsize_to_string, \
  File "C:\PROGRA~1/QGIS32~1.1/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\pyprecag\convert.py", line 26, in 
    from fiona import collection as fionacoll
  File "C:\PROGRA~1/QGIS32~1.1/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\fiona\__init__.py", line 86, in 
    from fiona.collection import BytesCollection, Collection
  File "C:\PROGRA~1/QGIS32~1.1/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\fiona\collection.py", line 11, in 
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
  File "C:\PROGRA~1/QGIS32~1.1/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: DLL load failed while importing ogrext: The specified module could not be found.

> Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.28.1-Firenze Firenze, fde3b8fbb8c 

> Python Path:
C:/PROGRA~1/QGIS32~1.1/apps/qgis/./python
%USERPROFILE%/AppData/Roaming/QGIS/QGIS3\profiles\default/python
%USERPROFILE%/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.1/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.28.1\bin\python39.zip
C:\PROGRA~1\QGIS32~1.1\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib
C:\Program Files\QGIS 3.28.1\bin
C:\PROGRA~1\QGIS32~1.1\apps\Python39
C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\Pythonwin
%USERPROFILE%/AppData/Roaming/QGIS/QGIS3\profiles\default/python
%USERPROFILE%\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pat

@cratcliff I'm not sure if this issue is related to pnugentmsu's but figured this would be the place to start. Is there additional info that would be useful for troubleshooting?

**Comment by cratcliff** [comment]
@lfrench0 , @pnugentmsu I have release a new version on the QGIS repository. Can you upgrade QGIS and install PAT and let me know if it fixes your issue.
