### ISSUE TITLE
Couldn't load plugin 'pat' due to an error when calling its classFactory() method 

### ISSUE THREAD

**Issue by wgivens1978** [CSIRO-Precision-Agriculture/PAT_QGIS_Plugin#70]
Getting the following error whn installing PAT:

Couldn't load plugin 'pat' due to an error when calling its classFactory() method 

AssertionError: Could not find PROJ_LIB directory 
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS33~1.2\apps\Python312\Lib\site-packages\pyprecag\__init__.py", line 65, in 
    proj_lib = pyproj.datadir.pyproj_datadir
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pyproj.datadir' has no attribute 'pyproj_datadir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 426, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/WadeGivens/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pat\__init__.py", line 94, in classFactory
    from pyprecag import config
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS33~1.2\apps\Python312\Lib\site-packages\pyprecag\__init__.py", line 73, in 
    assert os.path.isfile(
           ^^^^^^^^^^^^^^^
AssertionError: Could not find PROJ_LIB directory

Python version: 3.12.5 (main, Aug  8 2024, 11:21:54) [MSC v.1938 64 bit (AMD64)] 
QGIS version: 3.38.2-Grenoble Grenoble, 130c432394

**Comment by jose-renan-silva** [comment]
Obtive o mesmo problema

**Comment by Carlytax** [comment]
Hi! I have the same problem! Can fix them some day? I reinstall QGIS for solve it, but the error persist! 

              File "C:\PROGRA~1\QGIS33~1.3\apps\Python312\Lib\site-packages\pyprecag\__init__.py", line 65, in 
              proj_lib = pyproj.datadir.pyproj_datadir
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             AttributeError: module 'pyproj.datadir' has no attribute 'pyproj_datadir'
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\qgis\utils.py", line 426, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/Carla/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pat\__init__.py", line 94, in classFactory
              from pyprecag import config
              File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\qgis\utils.py", line 923, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\PROGRA~1\QGIS33~1.3\apps\Python312\Lib\site-packages\pyprecag\__init__.py", line 73, in 
              assert os.path.isfile(
              ^^^^^^^^^^^^^^^
             AssertionError: Could not find PROJ_LIB directory

2024-10-02T09:35:55     INFO    Estado de la aplicación:
             Variable de entorno QGIS_PREFIX_PATH: C:/PROGRA~1/QGIS33~1.3/apps/qgis
             Prefijo: C:/PROGRA~1/QGIS33~1.3/apps/qgis
             Ruta de complementos: C:/PROGRA~1/QGIS33~1.3/apps/qgis/plugins
             Ruta de datos del paquete: C:/PROGRA~1/QGIS33~1.3/apps/qgis/.
             Nombre del tema activo: default
             Ruta del tema activo: C:/PROGRA~1/QGIS33~1.3/apps/qgis/./resources/themes\default\icons/
             Ruta del tema predeterminado: :/images/themes/default/
             Rutas de búsqueda de SVG: C:/PROGRA~1/QGIS33~1.3/apps/qgis/./svg/
              C:/Users/Carla/AppData/Roaming/QGIS/QGIS3\profiles\default/svg/
             Ruta de la base de datos del usuario: C:/PROGRA~1/QGIS33~1.3/apps/qgis/./resources/qgis.db
             Ruta de la base de datos de autenticación: C:/Users/Carla/AppData/Roaming/QGIS/QGIS3\profiles\default/qgis-auth.db

**Comment by agrifella** [comment]
Same problem here, installed on a new system and continue to get the same errors. Tried older versions of plugin and QGIS without luck.

```
Couldn't load plugin 'pat' due to an error when calling its classFactory() method 

AssertionError: Could not find PROJ_LIB directory 
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS33~1.12\apps\Python312\Lib\site-packages\pyprecag\__init__.py", line 65, in 
    proj_lib = pyproj.datadir.pyproj_datadir
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pyproj.datadir' has no attribute 'pyproj_datadir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.12/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/Loic Allinson-Dunn/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pat\__init__.py", line 94, in classFactory
    from pyprecag import config
  File "C:\PROGRA~1/QGIS33~1.12/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS33~1.12\apps\Python312\Lib\site-packages\pyprecag\__init__.py", line 73, in 
    assert os.path.isfile(
           ^^^^^^^^^^^^^^^
AssertionError: Could not find PROJ_LIB directory


Python version: 3.12.7 (main, Oct 25 2024, 11:18:09) [MSC v.1938 64 bit (AMD64)] 
QGIS version: 3.34.12-Prizren Prizren, eeb6af3638 

Python Path:
C:/PROGRA~1/QGIS33~1.12/apps/qgis-ltr/./python
C:/Users/Loic Allinson-Dunn/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Loic Allinson-Dunn/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.12/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS33~1.12\apps\grass\grass84\etc\python
C:\Users\Loic Allinson-Dunn\Documents
C:\Program Files\QGIS 3.34.12\bin\python312.zip
C:\PROGRA~1\QGIS33~1.12\apps\Python312\DLLs
C:\PROGRA~1\QGIS33~1.12\apps\Python312\Lib
C:\Program Files\QGIS 3.34.12\bin
C:\PROGRA~1\QGIS33~1.12\apps\Python312
C:\PROGRA~1\QGIS33~1.12\apps\Python312\Lib\site-packages
C:\PROGRA~1\QGIS33~1.12\apps\Python312\Lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.12\apps\Python312\Lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.12\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/Loic Allinson-Dunn/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\Loic Allinson-Dunn\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pat
C:/Users/Loic Allinson-Dunn/OneDrive/Documents/fields/f58
```

**Comment by cratcliff** [comment]
@agrifella, @wgivens1978, @Carlytax, @jose-renan-silva I have just release a new version on the QGIS repository. Can you install it and let me know if it fixes your issue.

**Comment by dirtpan** [comment]
Fixed my issue!!
